# Generated by Django 4.1.3 on 2022-11-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
